# -*- coding: utf-8 -*-
"""condicoes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l3kcuMHqMutQrf4NxaMcQCN-oMHhHkvf
"""

'''i = 1
while i <= 50:
  print(i)
  i += 1
i = 1
while i <= 50:
  if i % 2 == 0:
    print(i)
  i += 1'''

i = 1; cp = 0; n1 = int(input('Digite o num1: ')); n2 = int(input('Digite o num2: '))
while True:
  if n1 % 2 == 0:
    n1 += 1
    cp += 1
    print(n1)
    if n1 > n2:
      break
print(cp)

'''
i = 1; r = 1; n = int(input("Digite um num: "))
while i <= n:
  r *= i; i += 1
print(r)'''