# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WShx6Lp4Yp6XqBTW_vb3hRFBos8oG2Bn
"""

'''#1
n = int(input("Digite um num: ")); print(n)

#2
n1 = int(input("Digite o 1° num: ")); n2 = int(input("Digite o 2° num: ")); n3 = int(input("Digite o 3° num: "))
print(f'A soma dos numeros digitados é {n1+n2+n3} ')

#3
n = int(input("Digite um numero: ")); s = n+1; a = n-1; print(f'O sucessor é {s} e o antecessor é {a}.')

#4
c = int(input("Digite a temperatura em Celcios: ")); f = c*1.8+32; print(f'A temperatura digitada em Fahrenheit é {f:.0f}°')

#5
k = float(input("Digite o kh/h: ")); m = k/3.6; print(f'{k:.1f}km/h convertirdos são {m:.1f}m/s')

#6
n1 = float(input("Digite a 1ª nota: "));n2 = float(input("Digite a 2ª nota: "));n3 = float(input("Digite a 3ª nota: "));n4 = float(input("Digite a 4ª nota: "))
n = (n1+n2+n3+n4)/4; print(f'A media aritmetica é {n:.1f}')

7#
r = float(input("Digite em reais para converter em dolar: ")); d = 5.17; c = r/d
print(f'{r:.0f} reais convertidos na cotação do dolar hoje de (5.17) é {c:.1f} dolares')

#8
r = float(input('Digite o valor do raio: ')); a = 3.14*r**2; print(f'A area do circulo é {a}')

9#
n = 780000/100; n1 = n*46; n2 = n*32; n3 = 780000-n1-n2; print(f'a){n1} b) {n2} c){n3}')

10#
n = int(input('Digite um num: '));
if n > 0:
  q = n**2; r = n**(1/2); print(f'O numero digitado ao quadrado é {q:.1f} e a raiz quadrada é {r:.1f}')
else:
  print('O numero digitado é negativo.')

#11
n = int(input('Digite um num: '))
if n > 0 and n%2 == 0:
  print('O numero digitado é PAR e POSITIVO')
if n > 0 and n%2 != 0:
  print('O numero digitado é IMPAR e POSITIVO')
if n < 0 and n%2 == 0:
  print('O numero digitado é PAR e NEGATIVO')
if n < 0 and n%2 != 0:
  print('O numero digitado é IMPAR e NEGATIVO')

#12
n1 = float(input('Digite a 1ª nota: ')); n2 = float(input('Digite a 2ª nota: '))
if n1 >= 0 and n1 <= 10 and n2 >= 0 and n2 <= 10:
  print(f'As notas digitadas sao: {n1} e {n2}')
else:
  print('Uma ou mais notas digitas foram invalidas.')'''