# -*- coding: utf-8 -*-
"""lista3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XSw37AbBu3AP3yonOWQ4tCVrUp37bk9n
"""

# #1
# n = int(input("Digite um num: ")); print(n)

# #2
# n1 = int(input("Digite o 1° num: ")); n2 = int(input("Digite o 2° num: ")); n3 = int(input("Digite o 3° num: "))
# print(f'A soma dos numeros digitados é {n1+n2+n3} ')

# #3
# n = int(input("Digite um numero: ")); s = n+1; a = n-1; print(f'O sucessor é {s} e o antecessor é {a}.')

# #4
# c = int(input("Digite a temperatura em Celcios: ")); f = c*1.8+32; print(f'A temperatura digitada em Fahrenheit é {f:.0f}°')

# #5
# k = float(input("Digite o kh/h: ")); m = k/3.6; print(f'{k:.1f}km/h convertirdos são {m:.1f}m/s')

# #6
# n1 = float(input("Digite a 1ª nota: "));n2 = float(input("Digite a 2ª nota: "));n3 = float(input("Digite a 3ª nota: "));n4 = float(input("Digite a 4ª nota: "))
# n = (n1+n2+n3+n4)/4; print(f'A media aritmetica é {n:.1f}')

# 7#
# r = float(input("Digite em reais para converter em dolar: ")); d = 5.17; c = r/d
# print(f'{r:.0f} reais convertidos na cotação do dolar hoje de (5.17) é {c:.1f} dolares')

# #8
# r = float(input('Digite o valor do raio: ')); a = 3.14*r**2; print(f'A area do circulo é {a}')

# 9#
# n = 780000/100; n1 = n*46; n2 = n*32; n3 = 780000-n1-n2; print(f'a){n1} b) {n2} c){n3}')

# 10#
# n = int(input('Digite um num: '));
# if n > 0:
#   q = n**2; r = n**(1/2); print(f'O numero digitado ao quadrado é {q:.1f} e a raiz quadrada é {r:.1f}')
# else:
#   print('O numero digitado é negativo.')

# #11
# n = int(input('Digite um num: '))
# if n > 0 and n%2 == 0:
#   print('O numero digitado é PAR e POSITIVO')
# if n > 0 and n%2 != 0:
#   print('O numero digitado é IMPAR e POSITIVO')
# if n < 0 and n%2 == 0:
#   print('O numero digitado é PAR e NEGATIVO')
# if n < 0 and n%2 != 0:
#   print('O numero digitado é IMPAR e NEGATIVO')

#12
# n1 = float(input('Digite a 1ª nota: ')); n2 = float(input('Digite a 2ª nota: '))
# if n1 >= 0 and n1 <= 10 and n2 >= 0 and n2 <= 10:
#   m=(n1+n2)/2; print(f'As notas digitadas sao: {n1} e {n2} e a sua media é {m}.')
# else:
#   print('Uma ou mais notas digitadas foram invalidas.')

# #13
# h = float(input('Digite sua altura: ')); s = input('Digite seu sexo M ou F: ')
# if s == str('F'):
#   peso_ideal = 62.1 * h - 44.7
#   print('O seu peso ideal é {:.2f}'.format(peso_ideal))
# elif s == str('M'):
#   peso_ideal = 72.7 * h - 58
#   print('O seu peso ideal é {:.2f}'.format(peso_ideal))
# elif s == str('m'):
#   sexo_MAI = str(s .upper())
#   peso_ideal = 72.7 * h - 58
#   print('O seu peso ideal é {:.2f}'.format(peso_ideal))
# elif s == str('f'):
#   sexo_MAI = str(s .upper())
#   peso_ideal = 62.1 * h - 44.7
#   print('O seu peso ideal é {:.2f}'.format(peso_ideal))
# else:
#   print('Digite o sexo corretamente M ou F.')

# #14
# tra = float(input('Digite a nota do trabalho: '))
# ava = float(input('Digite a nota da avaliaçao semestral: '))
# exa = float(input('Digite a nota da exame final: '))
# tra2 = tra * 2; ava2 = ava * 3; exa2 = exa * 5; media = (tra2 + ava2 + exa2) / 10
# if media < 3:
#   print('O estudante esta reprovado.')
# elif media < 5 and media >= 3:
#   print('O estudante esta em recuperaçao.')
# elif media >= 5:
#   print('O estudante esta aprovado.')

# #15
# print('Reponda apenas com S para sim e N para não.'); c = 0
# p1 = input('Telefonol para vitima?: ')
# p2 = input('Esteve no local do crime?: ')
# p3 = input('Mora perto da vitima?: ')
# p4 = input('Devia para vitima?: ')
# p5 = input('Ja trabalhou com a vitima?: ')
# if p1 == str('S'):
#   c += 1
# if p2 == str('S'):
#   c += 1
# if p3 == str('S'):
#   c += 1
# if p4 == str('S'):
#   c += 1
# if p5 == str('S'):
#   c += 1
# if c < 2:
#   print('Voce é considerado inocente.')
# if c == 2:
#   print('Voce é considerado suspeito.')
# if c <= 3 and c >= 4:
#   print('Voce é considerado cumplice.')
# if c >= 5:
#   print('Voce é considerado assassino.')

# #16
# i = int(input('Digite a sua idade: ')); t = int(input('Digite o tempo trabalhado: '))
# if i >= 65:
#   print('Tem idade para se aposentar.')
# elif t >= 30:
#   print('Tem tempo de trabalho suficiente para se aposentar')
# elif i >= 60 and t >= 25:
#   print('Tem idade e tempo de trabalho suficiente para se aposentar.')

# #17
# k = float(input('Digite quantos Km foi percorrido: '))
# l = float(input('Digite quantos litros foi consumido no percurso: ')); kml = k/l
# if kml < 8:
#   print('{:.2f}km/l Venda o carro!'.format(kml))
# elif kml >= 8 and kml <= 12:
#   print('{:.2f}km/l Economico!'.format(kml))
# elif kml > 12:
#   print('{:.2f}km/l Super econômico!'.format(kml))

# #18
# print('Utilizando for.')
# for i in range(1,101):
#     print(i)
# print('Utilizando while.'); i = 1
# while i <= 100:
#     print(i); i += 1

# #19
# s = 0
# for i in range(10):
#     v = int(input('Digite um valor: ')); s += v
# print(f'A soma dos valores é {s}.')

# #20
# s = 0
# for i in range(10):
#   v = int(input("Digite um numero: ")); s += v
# print(f'A media dos numeros digitados é {(s/10):.1f}.')

# #21
# sp = 0
# for i in range(10):
#   v = int(input("Digite um numero: "))
#   if v % 2 == 0:
#     sp += v
# print(f'A media dos numeros pares é {sp/10:.1f}.')

# #22
# n = int(input('Digite um numero: '))
# for i in range(1,n+1):
#   if i%2!=0:
#     print(i)

# #23
# n = int(input('Digite um numero: '))
# for i in range(0,n+1):
#   print(i)

# #24
# n = int(input('Digite um numero: ')); i=1
# while i <= n:
#   print(n-i)
#   i += 1

# #25
# n1 = int(input('Digite o num1: '));n2 = int(input('Digite o num2: '));sp=0;mi=1
# for i in range(n1,n2+1):
#   print(i)
#   if i%2==0:
#     sp+=i
#   else:
#     mi*=i
# print(f'A soma dos numeros pares entre {n1} e {n2} é {sp}\nA multiplicação dos numeros impares entre {n1} e {n2} é {mi}.')

#26
# o=1; n=1
# for i in range(1,10):
#   for o in range(1,11):
#     print(f'{n} X {o} = {n*o:.0f}')
#     o += 1
#   i += 1
#   n += 1
#   print('\n')
#   if i > 9:
#     break

# # #27
# n = int(input("Digite um num: ")); x=1; y=1; z=1 ; esp = ''
# for x in range (1,n+1):
#   for z in range(1,x+1):
#     esp+=(str(y)+(' ')); y+=1
#   print(esp); esp = ''