# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rQYzcQYmundyoBs1odJwH8dYF3chrfe4
"""

#QUESTAO 3
from os import remove
import random

palavras = []
cont_erros = 0
letras = []

with open('jogo_forca.txt', 'r') as arquivo:
    for valor in arquivo:
        str(valor)
        palavras.append(str(valor))

palavra_sorteada = random.choice(palavras)
con_let_pal = set(palavra_sorteada)
con_let_dig = set()

print('-=' * 30)
print((' ' * 21), 'JOGO DA FORCA')
print('-=' * 30)
print((' ' * 22), 'DiCA: PAÍS')
print('-=' * 30)
print()
print('Descubra a palavra -->  ', end='')

for valor in palavra_sorteada:
    print('_ ', end='')


while not con_let_pal.issubset(con_let_dig) and cont_erros < 7:
    let_dig = input(str('  Digite uma letra: '))
    con_let_dig.add(let_dig)
    if let_dig in con_let_pal:
        for letra in palavra_sorteada:
            if letra in con_let_dig:
                print(f'{letra} ', end='')
            else:
                print('_ ', end='')
        print(f'letras digitadas {let_dig}')
    else:
        cont_erros += 1
        print(f'Você errou pela {cont_erros}ª vez. Tente de novo! {cont_erros} de 6 erros')
        print(f'letras digitadas {let_dig}')
print()
if cont_erros > 6:
    print('-=' * 30)
    print('Voce perdeu. tente novamente :(')
    print('-=' * 30)
else:
    print('-=' * 30)
    print('Voce pganhou! :)')
    print('-=' * 30)